version: '3'

services:
  front:
    image: nginx:1.15.8-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: "always"
    ports:
      - 5000:80
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: "always"
  auth:
    build:
      dockerfile: ./docker/auth/Dockerfile
      context: ./
    restart: "always"
    env_file:
      - .env

  # accounts:
  #   build: ./docker/accounts/
  #   restart: "always"
  #   env_file:
  #     - .env
