// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/auth/pb/auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorResponse struct {
	// code is numeric code for the error that occured
	Code *wrappers.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// request_id is ID for tracing. use it in displaying errors and troubleshooting
	RequestId *wrappers.StringValue `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// error contains the human-readable description of the error
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2773301b15359e1, []int{0}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetCode() *wrappers.Int32Value {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ErrorResponse) GetRequestId() *wrappers.StringValue {
	if m != nil {
		return m.RequestId
	}
	return nil
}

func (m *ErrorResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// The request message containing the user's name.
type AuthRequest struct {
	// username need to contain user name
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// password need to contain password
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// code (optional) can contain code for authentication
	Code                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2773301b15359e1, []int{1}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthRequest) GetCode() *wrappers.StringValue {
	if m != nil {
		return m.Code
	}
	return nil
}

// AuthResponse - response to user authentication
type AuthResponse struct {
	// Types that are valid to be assigned to OneofValue:
	//	*AuthResponse_Error
	//	*AuthResponse_Message
	OneofValue           isAuthResponse_OneofValue `protobuf_oneof:"oneof_value"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2773301b15359e1, []int{2}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

type isAuthResponse_OneofValue interface {
	isAuthResponse_OneofValue()
}

type AuthResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type AuthResponse_Message struct {
	Message string `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
}

func (*AuthResponse_Error) isAuthResponse_OneofValue() {}

func (*AuthResponse_Message) isAuthResponse_OneofValue() {}

func (m *AuthResponse) GetOneofValue() isAuthResponse_OneofValue {
	if m != nil {
		return m.OneofValue
	}
	return nil
}

func (m *AuthResponse) GetError() *ErrorResponse {
	if x, ok := m.GetOneofValue().(*AuthResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *AuthResponse) GetMessage() string {
	if x, ok := m.GetOneofValue().(*AuthResponse_Message); ok {
		return x.Message
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AuthResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AuthResponse_Error)(nil),
		(*AuthResponse_Message)(nil),
	}
}

func init() {
	proto.RegisterType((*ErrorResponse)(nil), "ErrorResponse")
	proto.RegisterType((*AuthRequest)(nil), "AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "AuthResponse")
}

func init() { proto.RegisterFile("core/auth/pb/auth.proto", fileDescriptor_d2773301b15359e1) }

var fileDescriptor_d2773301b15359e1 = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x5e, 0x5b, 0xfe, 0xea, 0x6e, 0xa3, 0x58, 0x13, 0x4c, 0x65, 0x42, 0x96, 0x85, 0xc6, 0xb4,
	0x2d, 0x3f, 0x6d, 0x33, 0x18, 0xe5, 0xaa, 0x9b, 0x98, 0xb6, 0x1b, 0x34, 0x52, 0x89, 0xdb, 0xc9,
	0x4d, 0x4e, 0xd3, 0x40, 0x66, 0x07, 0xdb, 0x59, 0x84, 0x80, 0x1b, 0xde, 0x80, 0xf1, 0x2e, 0x5c,
	0xf0, 0x18, 0xf0, 0x0a, 0x3c, 0x08, 0x72, 0x92, 0x8e, 0xc1, 0x8a, 0x84, 0x14, 0xc9, 0x39, 0x3e,
	0xdf, 0xe7, 0x73, 0xce, 0xf7, 0x1d, 0x74, 0x2f, 0x10, 0x12, 0x1c, 0x96, 0xe9, 0xa9, 0x93, 0x8e,
	0x8b, 0xd3, 0x4e, 0xa5, 0xd0, 0xa2, 0xb3, 0x16, 0x09, 0x11, 0x25, 0xe0, 0xb0, 0x34, 0x76, 0x18,
	0xe7, 0x42, 0x33, 0x1d, 0x0b, 0xae, 0xaa, 0xec, 0x76, 0x71, 0x04, 0x56, 0x04, 0xdc, 0x52, 0x39,
	0x8b, 0x22, 0x90, 0x8e, 0x48, 0x0b, 0xc4, 0x1c, 0xf4, 0x83, 0xea, 0xad, 0x22, 0x1a, 0x67, 0x13,
	0x27, 0x97, 0x2c, 0x4d, 0x41, 0x56, 0x79, 0xfa, 0xb9, 0x8e, 0x96, 0x9e, 0x4b, 0x29, 0xa4, 0x0f,
	0x2a, 0x15, 0x5c, 0x01, 0x76, 0xd0, 0xb5, 0x40, 0x84, 0xb0, 0x5a, 0x23, 0xb5, 0x8d, 0x56, 0xef,
	0xbe, 0x5d, 0x3e, 0x60, 0xcf, 0x1e, 0xb0, 0x8f, 0xb8, 0xee, 0xf7, 0x5e, 0xb1, 0x24, 0x03, 0xbf,
	0x00, 0xe2, 0x67, 0x08, 0x49, 0x78, 0x9b, 0x81, 0xd2, 0x27, 0x71, 0xb8, 0x5a, 0x2f, 0x68, 0x6b,
	0x57, 0x68, 0x23, 0x2d, 0x63, 0x1e, 0x95, 0xbc, 0x66, 0x85, 0x3f, 0x0a, 0xf1, 0x0a, 0xba, 0x0e,
	0xa6, 0xfc, 0x6a, 0x83, 0xd4, 0x36, 0x9a, 0x7e, 0x19, 0x0c, 0x3e, 0x9c, 0x0f, 0xdf, 0x21, 0xf4,
	0xbd, 0x76, 0xf3, 0x14, 0x94, 0x62, 0x11, 0xf4, 0xde, 0xe0, 0xf8, 0x3d, 0xa1, 0xa6, 0x1c, 0x1d,
	0x90, 0xbe, 0xeb, 0xba, 0xdb, 0x84, 0x56, 0x39, 0x3a, 0x20, 0x74, 0x24, 0x4e, 0x41, 0x4f, 0x63,
	0x1e, 0x91, 0x1c, 0xb8, 0x26, 0xb9, 0x14, 0x3c, 0xa2, 0xdb, 0x84, 0xfe, 0xee, 0xcb, 0xa0, 0xdc,
	0x60, 0xd2, 0x7f, 0xdc, 0x85, 0xae, 0xe5, 0x8d, 0x3d, 0xcf, 0xf2, 0x76, 0xfb, 0xa1, 0xc5, 0xba,
	0x3b, 0x4f, 0xad, 0x1d, 0x2f, 0x64, 0xe3, 0x70, 0xf2, 0x04, 0x76, 0xbb, 0x1e, 0x25, 0x1f, 0x69,
	0x8e, 0x5a, 0xc3, 0x4c, 0x4f, 0xfd, 0x92, 0x8c, 0x3b, 0xe8, 0x56, 0xa6, 0x40, 0x72, 0x76, 0x5a,
	0x8a, 0xd2, 0xf4, 0x2f, 0x62, 0x93, 0x4b, 0x99, 0x52, 0xb9, 0x90, 0xe5, 0xe4, 0x4d, 0xff, 0x22,
	0xc6, 0x6e, 0x25, 0x64, 0xe3, 0x3f, 0x14, 0x29, 0x90, 0x94, 0xa1, 0xc5, 0xb2, 0x70, 0x65, 0xc5,
	0xfa, 0x4c, 0x9c, 0xd2, 0x8b, 0x65, 0xfb, 0x0f, 0xa7, 0x0e, 0x17, 0x2a, 0xb9, 0x70, 0x07, 0xcd,
	0x84, 0x2a, 0x9b, 0x38, 0x5c, 0xf0, 0x67, 0x17, 0x7b, 0x4b, 0xa8, 0x25, 0x38, 0x88, 0xc9, 0xc9,
	0x99, 0x29, 0xd4, 0x7b, 0x59, 0xce, 0x36, 0x02, 0x79, 0x16, 0x07, 0x80, 0xf7, 0x50, 0x6b, 0x18,
	0x04, 0x22, 0xe3, 0xda, 0xdc, 0xe2, 0x45, 0xfb, 0xd2, 0xe0, 0x9d, 0x25, 0xfb, 0x72, 0x37, 0xf4,
	0xee, 0xa7, 0x1f, 0x3f, 0xbf, 0xd4, 0xdb, 0x74, 0xd9, 0x61, 0x25, 0x45, 0x15, 0x4b, 0xbb, 0xf7,
	0xad, 0x7e, 0x3e, 0xfc, 0x5a, 0xc7, 0xfb, 0xe8, 0xb6, 0xb1, 0x81, 0x64, 0x0a, 0x26, 0x59, 0x42,
	0x86, 0xc7, 0x47, 0x78, 0x4b, 0x4f, 0x63, 0x65, 0xfe, 0x48, 0xce, 0x14, 0x51, 0x59, 0x9a, 0x0a,
	0x05, 0x44, 0x0b, 0x12, 0x9a, 0x6f, 0x66, 0x59, 0x49, 0xe8, 0x35, 0xba, 0xb6, 0xdb, 0x69, 0x26,
	0x22, 0x60, 0xc9, 0x54, 0x28, 0xbd, 0x59, 0xab, 0xf7, 0xda, 0x2c, 0x4d, 0x93, 0x38, 0x28, 0x16,
	0xda, 0x79, 0xad, 0x04, 0x1f, 0x5c, 0xb9, 0xf1, 0xbb, 0xa8, 0xe1, 0xb9, 0x2e, 0xde, 0x44, 0x2b,
	0xfb, 0x49, 0x6c, 0xcc, 0xaf, 0xba, 0x27, 0x85, 0x56, 0x18, 0xa3, 0x76, 0xe7, 0x2f, 0xdd, 0x7c,
	0xcb, 0x50, 0xfa, 0x78, 0x1d, 0xb5, 0x87, 0x41, 0x00, 0x4a, 0x91, 0x03, 0x21, 0xc7, 0x71, 0x18,
	0x02, 0x9f, 0x0b, 0xdf, 0x32, 0x70, 0x0f, 0x3f, 0x44, 0xcb, 0xc7, 0x2c, 0x02, 0xf2, 0x42, 0x68,
	0x72, 0x20, 0x32, 0x1e, 0xce, 0x05, 0xdb, 0xa8, 0xb1, 0xe3, 0xba, 0xf8, 0x11, 0xba, 0x63, 0x24,
	0x06, 0x49, 0x46, 0x71, 0x08, 0xff, 0xee, 0x65, 0x7c, 0xa3, 0x58, 0x87, 0xfe, 0xaf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xea, 0x2e, 0x99, 0x66, 0x0d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	// AccountAuth is a public endpoint for authorization
	AccountAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) AccountAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/AuthService/AccountAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	// AccountAuth is a public endpoint for authorization
	AccountAuth(context.Context, *AuthRequest) (*AuthResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) AccountAuth(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountAuth not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_AccountAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AccountAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/AccountAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AccountAuth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountAuth",
			Handler:    _AuthService_AccountAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/auth/pb/auth.proto",
}
