// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/auth/pb/auth.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type AuthRequest struct {
	// username need to contain user name
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// password need to contain password
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// code (optional) can contain code for authentication
	Code                 *wrappers.StringValue `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2773301b15359e1, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthRequest) GetCode() *wrappers.StringValue {
	if m != nil {
		return m.Code
	}
	return nil
}

// AuthResponse - response to user authentication
type AuthResponse struct {
	// message can contain example
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2773301b15359e1, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "pb.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "pb.AuthResponse")
}

func init() { proto.RegisterFile("core/auth/pb/auth.proto", fileDescriptor_d2773301b15359e1) }

var fileDescriptor_d2773301b15359e1 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0xed, 0x2a, 0x7e, 0xa4, 0x82, 0x92, 0x8b, 0xa5, 0x88, 0x2c, 0x3d, 0xf5, 0x94, 0x4a,
	0x7d, 0x82, 0xbe, 0x42, 0x17, 0xbc, 0x27, 0xd9, 0xb1, 0xbb, 0xb0, 0xdb, 0x19, 0x67, 0x12, 0xfb,
	0xfa, 0xd2, 0x86, 0xea, 0x9e, 0xc2, 0xff, 0x83, 0xfc, 0xfe, 0xa3, 0x5e, 0x3c, 0x32, 0x34, 0x36,
	0x86, 0x43, 0x43, 0x6e, 0x79, 0x0d, 0x31, 0x06, 0xd4, 0x1b, 0x72, 0xe5, 0xdb, 0x80, 0x38, 0x9c,
	0xa0, 0x59, 0x1c, 0x17, 0xbf, 0x9a, 0x89, 0x2d, 0x11, 0xb0, 0xa4, 0x4e, 0x35, 0xa9, 0xbc, 0x8b,
	0xe1, 0xd0, 0xc3, 0x77, 0x04, 0x09, 0xba, 0x54, 0xf7, 0x51, 0x80, 0x47, 0x7b, 0x86, 0x22, 0xdb,
	0x66, 0xf5, 0x43, 0xff, 0xa7, 0xe7, 0x8c, 0xac, 0xc8, 0x84, 0xbc, 0x2f, 0x36, 0x29, 0x5b, 0xb5,
	0x7e, 0x57, 0x37, 0x1e, 0xf7, 0x50, 0x5c, 0x6f, 0xb3, 0x3a, 0x6f, 0x5f, 0x4d, 0xa2, 0x9a, 0x95,
	0x6a, 0x76, 0x81, 0x8f, 0xe3, 0xf0, 0x69, 0x4f, 0x11, 0xfa, 0xa5, 0x59, 0xd5, 0xea, 0x31, 0x81,
	0x85, 0x70, 0x14, 0xd0, 0x85, 0xba, 0x3b, 0x83, 0x88, 0x1d, 0x56, 0xf0, 0x2a, 0xdb, 0x2e, 0x4d,
	0xdc, 0x01, 0xff, 0x1c, 0x3d, 0xe8, 0x56, 0xe5, 0x9d, 0xf7, 0x18, 0xc7, 0x30, 0xbb, 0xfa, 0xc9,
	0x90, 0x33, 0x17, 0x27, 0x94, 0xcf, 0xff, 0x46, 0xfa, 0xba, 0xba, 0x72, 0xb7, 0xcb, 0x90, 0x8f,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xd2, 0x8c, 0xd5, 0x2b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	// AccountAuth
	AccountAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) AccountAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthService/AccountAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	// AccountAuth
	AccountAuth(context.Context, *AuthRequest) (*AuthResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) AccountAuth(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountAuth not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_AccountAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AccountAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthService/AccountAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AccountAuth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountAuth",
			Handler:    _AuthService_AccountAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/auth/pb/auth.proto",
}
